version: '3.12.2'

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  flask_app:
    build: .
    container_name: flask_mongo_crud
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - .env

volumes:
  mongo_data:
